import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import {cn} from '@/lib/utils'
import "./globals.css";
import Providers from "@/components/providers";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"], variable: '--font-sans' });
const playfair = Playfair_Display({
  subsets:['latin'],
  variable: '--font-serif'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
    //these are the root HTML and body tag that wraps the entire application or all the pages.
    //passing the nested pages and layouts here to the body
    <html lang="en" suppressHydrationWarning>
      <body 
        className={cn(
          'flex min-h-screen flex-col font-sans antialiased',
          inter.variable,
          playfair.variable
        )}
      >
        <Providers>
          <Header />
          <main className="grow">{children}</main>
          <Footer />
        </Providers>
        </body> 
    </html>
  );
}
